### ISSUE TITLE
Bundling with Xdebug?

### ISSUE THREAD

**Issue by derickr** [pounard/xtrace2fg#1]
Hi,

I've always wanted this as a option in Xdebug itself. Perhaps are you interested in implementing this as another trace format in Xdebug? Trace formats aren't very hard to implement, have a look at: https://github.com/xdebug/xdebug/blob/master/xdebug_trace_computerized.c 

Or perhaps it makes sense to bundle this in the contrib/ directory?

Feel free to shoot me an email to chat.

cheers,
Derick

**Comment by pounard** [comment]
Hello ! I never saw your issue until now (4 years later, sorry). Indeed you're right, nevertheless, I know how to read C, but long time I didn't write some, I'll try someday.

**Comment by pounard** [comment]
I'm closing this issue, see you on the other side.
